apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://github.com/wexire/homelab
      targetRevision: feat/initial-setup
      path: charts/microservice
      helm:
        releaseName: portfolio
        valueFiles:
          - $homelab/k8s/apps/portfolio/values.yaml
        parameters:
          - name: commitSha
            value: $ARGOCD_APP_REVISION
    - repoURL: https://github.com/wexire/homelab
      targetRevision: feat/initial-setup
      ref: homelab
  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
